package SRL.oracle.apps.fnd.file.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileSetupVORowImpl extends OAViewRowImpl {
    public static final int SRLFILESETUPID = 0;
    public static final int SRLFILEGROUPID = 1;
    public static final int SRLFILEGROUPNAME = 2;
    public static final int SRLFILESUBGROUPNAME = 3;
    public static final int SRLFILESUBGROUPDESCRIPTION = 4;
    public static final int SRLFILESIZEALLOWED = 5;
    public static final int SRLFILEALLOWEDEXTENTION = 6;
    public static final int SRLFILESERVERPATH = 7;

    /**This is the default constructor (do not remove)
     */
    public FileSetupVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute SrlFileSetupId
     */
    public String getSrlFileSetupId() {
        return (String) getAttributeInternal(SRLFILESETUPID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileSetupId
     */
    public void setSrlFileSetupId(String value) {
        setAttributeInternal(SRLFILESETUPID, value);
    }

    /**Gets the attribute value for the calculated attribute SrlFileGroupId
     */
    public Number getSrlFileGroupId() {
        return (Number) getAttributeInternal(SRLFILEGROUPID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileGroupId
     */
    public void setSrlFileGroupId(Number value) {
        setAttributeInternal(SRLFILEGROUPID, value);
    }

    /**Gets the attribute value for the calculated attribute SrlFileGroupName
     */
    public String getSrlFileGroupName() {
        return (String) getAttributeInternal(SRLFILEGROUPNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileGroupName
     */
    public void setSrlFileGroupName(String value) {
        setAttributeInternal(SRLFILEGROUPNAME, value);
    }

    /**Gets the attribute value for the calculated attribute SrlFileSubGroupName
     */
    public String getSrlFileSubGroupName() {
        return (String) getAttributeInternal(SRLFILESUBGROUPNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileSubGroupName
     */
    public void setSrlFileSubGroupName(String value) {
        setAttributeInternal(SRLFILESUBGROUPNAME, value);
    }

    /**Gets the attribute value for the calculated attribute SrlFileSubGroupDescription
     */
    public String getSrlFileSubGroupDescription() {
        return (String) getAttributeInternal(SRLFILESUBGROUPDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileSubGroupDescription
     */
    public void setSrlFileSubGroupDescription(String value) {
        setAttributeInternal(SRLFILESUBGROUPDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute SrlFileSizeAllowed
     */
    public Number getSrlFileSizeAllowed() {
        return (Number) getAttributeInternal(SRLFILESIZEALLOWED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileSizeAllowed
     */
    public void setSrlFileSizeAllowed(Number value) {
        setAttributeInternal(SRLFILESIZEALLOWED, value);
    }

    /**Gets the attribute value for the calculated attribute SrlFileAllowedExtention
     */
    public String getSrlFileAllowedExtention() {
        return (String) getAttributeInternal(SRLFILEALLOWEDEXTENTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileAllowedExtention
     */
    public void setSrlFileAllowedExtention(String value) {
        setAttributeInternal(SRLFILEALLOWEDEXTENTION, value);
    }

    /**Gets the attribute value for the calculated attribute SrlFileServerPath
     */
    public String getSrlFileServerPath() {
        return (String) getAttributeInternal(SRLFILESERVERPATH);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SrlFileServerPath
     */
    public void setSrlFileServerPath(String value) {
        setAttributeInternal(SRLFILESERVERPATH, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SRLFILESETUPID:
            return getSrlFileSetupId();
        case SRLFILEGROUPID:
            return getSrlFileGroupId();
        case SRLFILEGROUPNAME:
            return getSrlFileGroupName();
        case SRLFILESUBGROUPNAME:
            return getSrlFileSubGroupName();
        case SRLFILESUBGROUPDESCRIPTION:
            return getSrlFileSubGroupDescription();
        case SRLFILESIZEALLOWED:
            return getSrlFileSizeAllowed();
        case SRLFILEALLOWEDEXTENTION:
            return getSrlFileAllowedExtention();
        case SRLFILESERVERPATH:
            return getSrlFileServerPath();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
