package SRL.oracle.apps.fnd.ImportFromExcel.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImportExcelAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public ImportExcelAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("SRL.oracle.apps.fnd.ImportFromExcel.server", /* package name */
      "ImportExcelAMLocal" /* Configuration Name */);
    }

    /**Container's getter for SetUpView1
     */
    public SetUpViewImpl getSetUpView1() {
        return (SetUpViewImpl)findViewObject("SetUpView1");
    }

    /**Container's getter for DashBoardView1
     */
    public DashBoardViewImpl getDashBoardView1() {
        return (DashBoardViewImpl)findViewObject("DashBoardView1");
    }
}
